name: Run project test
on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
  page_build:
    release:
      types:
        - created

jobs:
  BuildAndTest: # Job name
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }} # Operating system selection
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup-scala
        uses: olafurpg/setup-scala@v10
      - name: Compile
        run: sbt compile
      - name: Test
        run: sbt -v +test